// src/lib/components/CountDown.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { fly } from 'svelte/transition';
	import { CURRENT_YEAR } from '../data/constants';
	import { _ } from 'svelte-i18n';

	const targetDate = new Date(`${CURRENT_YEAR + 1}-01-01T00:00:00`);

	let timeLeft = {
		days: 0,
		hours: 0,
		minutes: 0,
		seconds: 0
	};

	let interval: ReturnType<typeof setInterval>;

	function updateCountdown() {
		const now = new Date();
		const difference = targetDate.getTime() - now.getTime();

		if (difference > 0) {
			timeLeft = {
				days: Math.floor(difference / (1000 * 60 * 60 * 24)),
				hours: Math.floor((difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60)),
				minutes: Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60)),
				seconds: Math.floor((difference % (1000 * 60)) / 1000)
			};
		} else {
			timeLeft = { days: 0, hours: 0, minutes: 0, seconds: 0 };
			if (interval) clearInterval(interval);
		}
	}

	onMount(() => {
		updateCountdown();
		interval = setInterval(updateCountdown, 1000);
	});

	onDestroy(() => {
		if (interval) clearInterval(interval);
	});
</script>

<div class="flex flex-col items-center space-y-4 sm:space-y-6">
	<div class="grid w-full max-w-6xl grid-cols-2 gap-3 sm:gap-4 md:grid-cols-4 md:gap-6 lg:gap-8 xl:gap-10">
		<!-- Days -->
		<div class="flex flex-col items-center space-y-2 sm:space-y-3">
			<div
				class="relative flex h-20 w-20 items-center justify-center overflow-hidden rounded-xl border border-zinc-200/50 bg-zinc-100/30 p-4 backdrop-blur-sm transition-all duration-300 sm:h-24 sm:w-24 md:h-28 md:w-28 lg:h-32 lg:w-32 dark:border-zinc-800/80 dark:bg-zinc-900/30"
			>
				{#key timeLeft.days}
					<span
						in:fly={{ y: 20, duration: 400, delay: 300 }}
						out:fly={{ y: -20, duration: 300 }}
						class="number-glow absolute font-mono text-2xl font-bold text-zinc-800 sm:text-3xl md:text-4xl lg:text-5xl xl:text-6xl dark:text-zinc-100"
					>
						{timeLeft.days.toString().padStart(2, '0')}
					</span>
				{/key}
			</div>
			<span
				class="text-xs tracking-wider text-zinc-600 uppercase sm:text-sm md:text-base dark:text-zinc-400"
			>
				{$_('countdown.days')}
			</span>
		</div>

		<!-- Hours -->
		<div class="flex flex-col items-center space-y-2 sm:space-y-3">
			<div
				class="relative flex h-20 w-20 items-center justify-center overflow-hidden rounded-xl border border-zinc-200/50 bg-zinc-100/30 p-4 backdrop-blur-sm transition-all duration-300 sm:h-24 sm:w-24 md:h-28 md:w-28 lg:h-32 lg:w-32 dark:border-zinc-800/80 dark:bg-zinc-900/30"
			>
				{#key timeLeft.hours}
					<span
						in:fly={{ y: 20, duration: 400, delay: 300 }}
						out:fly={{ y: -20, duration: 300 }}
						class="number-glow absolute font-mono text-2xl font-bold text-zinc-800 sm:text-3xl md:text-4xl lg:text-5xl xl:text-6xl dark:text-zinc-100"
					>
						{timeLeft.hours.toString().padStart(2, '0')}
					</span>
				{/key}
			</div>
			<span
				class="text-xs tracking-wider text-zinc-600 uppercase sm:text-sm md:text-base dark:text-zinc-400"
			>
				{$_('countdown.hours')}
			</span>
		</div>

		<!-- Minutes -->
		<div class="flex flex-col items-center space-y-2 sm:space-y-3">
			<div
				class="relative flex h-20 w-20 items-center justify-center overflow-hidden rounded-xl border border-zinc-200/50 bg-zinc-100/30 p-4 backdrop-blur-sm transition-all duration-300 sm:h-24 sm:w-24 md:h-28 md:w-28 lg:h-32 lg:w-32 dark:border-zinc-800/80 dark:bg-zinc-900/30"
			>
				{#key timeLeft.minutes}
					<span
						in:fly={{ y: 20, duration: 400, delay: 300 }}
						out:fly={{ y: -20, duration: 300 }}
						class="number-glow absolute font-mono text-2xl font-bold text-zinc-800 sm:text-3xl md:text-4xl lg:text-5xl xl:text-6xl dark:text-zinc-100"
					>
						{timeLeft.minutes.toString().padStart(2, '0')}
					</span>
				{/key}
			</div>
			<span
				class="text-xs tracking-wider text-zinc-600 uppercase sm:text-sm md:text-base dark:text-zinc-400"
			>
				{$_('countdown.minutes')}
			</span>
		</div>

		<!-- Seconds -->
		<div class="flex flex-col items-center space-y-2 sm:space-y-3">
			<div
				class="relative flex h-20 w-20 items-center justify-center overflow-hidden rounded-xl border border-zinc-200/50 bg-zinc-100/30 p-4 backdrop-blur-sm transition-all duration-300 sm:h-24 sm:w-24 md:h-28 md:w-28 lg:h-32 lg:w-32 dark:border-zinc-800/80 dark:bg-zinc-900/30"
			>
				{#key timeLeft.seconds}
					<span
						in:fly={{ y: 20, duration: 400, delay: 300 }}
						out:fly={{ y: -20, duration: 300 }}
						class="number-glow absolute font-mono text-2xl font-bold text-zinc-800 sm:text-3xl md:text-4xl lg:text-5xl xl:text-6xl dark:text-zinc-100"
					>
						{timeLeft.seconds.toString().padStart(2, '0')}
					</span>
				{/key}
			</div>
			<span
				class="text-xs tracking-wider text-zinc-600 uppercase sm:text-sm md:text-base dark:text-zinc-400"
			>
				{$_('countdown.seconds')}
			</span>
		</div>
	</div>
</div>

<style>
	.number-glow {
		text-shadow:
			0 0 5px rgba(125, 211, 252, 0.4),
			0 0 10px rgba(125, 211, 252, 0.3),
			0 0 20px rgba(56, 189, 248, 0.2);
	}
	.dark .number-glow {
		text-shadow:
			0 0 5px rgba(14, 165, 233, 0.5),
			0 0 10px rgba(14, 165, 233, 0.4),
			0 0 20px rgba(56, 189, 248, 0.3);
	}
</style>

// components/countdown/count-down.tsx
'use client';

import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Card, CardContent } from '@/components/ui/card';
import NumberFlow, { Format } from '@number-flow/react';
import '@fontsource/share-tech-mono';

export default function CountdownTimer() {
  const [days, setDays] = useState(0);
  const [hours, setHours] = useState(0);
  const [minutes, setMinutes] = useState(0);
  const [seconds, setSeconds] = useState(0);

  useEffect(() => {
    const targetDate = new Date('2026-01-01T00:00:00');
    const interval = setInterval(() => {
      const now = new Date();
      const difference = targetDate.getTime() - now.getTime();

      if (difference <= 0) {
        setDays(0);
        setHours(0);
        setMinutes(0);
        setSeconds(0);
        clearInterval(interval);
        return;
      }

      const d = Math.floor(difference / (1000 * 60 * 60 * 24));
      const h = Math.floor(
        (difference % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60),
      );
      const m = Math.floor((difference % (1000 * 60 * 60)) / (1000 * 60));
      const s = Math.floor((difference % (1000 * 60)) / 1000);

      setDays(d);
      setHours(h);
      setMinutes(m);
      setSeconds(s);
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const timeUnits = [
    { value: days, label: 'Days', formatDigits: 3 },
    { value: hours, label: 'Hours', formatDigits: 2 },
    { value: minutes, label: 'Minutes', formatDigits: 2 },
    { value: seconds, label: 'Seconds', formatDigits: 2 },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      className="w-full max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8"
    >
      <h1 className="text-3xl md:text-4xl font-bold text-center mb-10 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 via-blue-400 to-cyan-400 font-['Share_Tech_Mono'] tracking-wider">
        Countdown to 2026
      </h1>
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4 md:gap-6">
        {timeUnits.map((unit, index) => (
          <motion.div
            key={unit.label}
            whileHover={{ y: -4, transition: { duration: 0.2 } }}
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.4, delay: index * 0.08, ease: 'easeOut' }}
            className="h-full flex"
          >
            <Card className="w-full flex flex-col bg-gradient-to-br from-gray-900/70 to-black/80 backdrop-blur-md border border-white/10 shadow-lg hover:border-blue-400/50 transition-colors duration-300 rounded-lg overflow-hidden">
              <CardContent className="flex-grow flex flex-col items-center justify-center p-4 md:p-6">
                <NumberFlow
                  value={unit.value}
                  className="text-5xl sm:text-6xl font-['Share_Tech_Mono'] font-bold text-sky-300 tracking-wider [text-shadow:0_0_10px_rgba(59,130,246,0.4)]"
                  format={`0${unit.formatDigits}` as Format}
                />
                <span className="text-xs text-gray-400 mt-3 uppercase tracking-wider font-['Share_Tech_Mono']">
                  {unit.label}
                </span>
              </CardContent>
            </Card>
          </motion.div>
        ))}
      </div>
    </motion.div>
  );
}
