// src/components/footer.tsx
import React from "react";
import { motion } from "motion/react";
import { Github, Heart, Coffee, Ship } from "lucide-react";
import { cn } from "@/lib/utils";

interface FooterProps {
  className?: string;
}

export default function Footer({ className }: FooterProps) {
  const currentYear = new Date().getFullYear();

  return (
    <motion.footer
      className={cn(
        "w-full mt-16 py-8 px-4 relative overflow-hidden",
        className
      )}
      initial={{ opacity: 0, y: 50 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.8, delay: 1.5 }}
    >
      {/* Background gradient */}
      <div className="absolute inset-0 bg-gradient-to-t from-blue-50/50 to-transparent dark:from-blue-950/20 dark:to-transparent" />

      <div className="relative z-10 max-w-4xl mx-auto">
        {/* Decorative wave */}
        <motion.div
          className="mb-6"
          animate={{
            y: [0, -5, 0],
          }}
          transition={{
            duration: 3,
            repeat: Infinity,
            ease: "easeInOut",
          }}
        >
          <svg
            className="w-full h-8 text-blue-300/50 dark:text-blue-600/30"
            viewBox="0 0 400 40"
            xmlns="http://www.w3.org/2000/svg"
          >
            <motion.path
              d="M0,20 Q100,10 200,20 T400,20"
              stroke="currentColor"
              strokeWidth="2"
              fill="none"
              animate={{
                d: [
                  "M0,20 Q100,10 200,20 T400,20",
                  "M0,25 Q100,15 200,25 T400,25",
                  "M0,20 Q100,10 200,20 T400,20",
                ],
              }}
              transition={{
                duration: 4,
                repeat: Infinity,
                ease: "easeInOut",
              }}
            />
          </svg>
        </motion.div>

        <div className="text-center space-y-6">
          {/* Main footer content */}
          <motion.div
            className="flex flex-col sm:flex-row items-center justify-center gap-4 text-sm text-gray-600 dark:text-gray-400"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 1.7 }}
          >
            <div className="flex items-center gap-2">
              <Ship className="w-4 h-4 text-blue-500" />
              <span>Sailing through {currentYear + 1}</span>
            </div>
            <span className="hidden sm:inline">•</span>
            <div className="flex items-center gap-2">
              <span>Made with</span>
              GerardABC
            </div>
          </motion.div>

          {/* Links */}
          <motion.div
            className="flex items-center justify-center gap-6"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 1.9 }}
          >
            <motion.a
              href="https://github.com/gerardbourguett/nye.today"
              target="_blank"
              rel="noopener noreferrer"
              className="flex items-center gap-2 text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 transition-colors duration-200"
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
            >
              <Github className="w-5 h-5" />
              <span className="text-sm font-medium">Source</span>
            </motion.a>
          </motion.div>

          {/* Inspirational quote */}
          <motion.div
            className="pt-4 border-t border-gray-200/50 dark:border-gray-700/50"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 2.1 }}
          >
            <motion.p
              className="text-xs italic text-gray-500 dark:text-gray-400 max-w-md mx-auto"
              animate={{
                opacity: [0.7, 1, 0.7],
              }}
              transition={{
                duration: 3,
                repeat: Infinity,
                ease: "easeInOut",
              }}
            >
              "The Spanish Galleon arrived, Leaving a wake in the sea. Its flag
              in the air, Its distinguished figure, Will conquer your world."
              <br />
              <a
                href="https://es.wikipedia.org/wiki/Tommy_Rey"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-2 block"
              >
                <span className="text-blue-500 dark:text-blue-400 font-medium">
                  — Tommy Rey
                </span>
              </a>
            </motion.p>
          </motion.div>

          {/* Floating elements */}
          <div className="absolute top-0 left-0 w-full h-full pointer-events-none overflow-hidden">
            {[...Array(3)].map((_, i) => (
              <motion.div
                key={i}
                className="absolute w-1 h-1 bg-blue-400/30 rounded-full"
                style={{
                  left: `${20 + i * 30}%`,
                  top: `${20 + i * 15}%`,
                }}
                animate={{
                  y: [0, -20, 0],
                  opacity: [0.3, 0.8, 0.3],
                }}
                transition={{
                  duration: 3,
                  delay: i * 0.5,
                  repeat: Infinity,
                  ease: "easeInOut",
                }}
              />
            ))}
          </div>
        </div>
      </div>
    </motion.footer>
  );
}

// src/lib/components/Footer.svelte
<script lang="ts">
	import { CURRENT_YEAR } from '../data/constants';
	import { Github, Coffee, Twitch, Twitter, Heart, Globe, Star } from '@lucide/svelte';
	import { _ } from 'svelte-i18n';
</script>

<footer
	class="relative mt-12 w-full overflow-hidden border-t border-zinc-200/50 bg-gradient-to-b from-transparent to-zinc-50/50 px-4 pt-8 pb-6 transition-all duration-300 dark:border-zinc-800/50 dark:to-zinc-900/30"
>
	<!-- Decorative gradient line -->
	<div
		class="absolute top-0 left-1/2 h-px w-32 -translate-x-1/2 bg-gradient-to-r from-transparent via-sky-400/60 to-transparent"
	></div>

	<!-- Main content container -->
	<div class="mx-auto max-w-6xl">
		<!-- Social links section -->
		<div class="mb-8">
			<div class="mb-6 text-center">
				<h3 class="mb-2 text-sm font-semibold text-zinc-700 dark:text-zinc-300">
					{$_('footer.connect_with_us') || 'Connect with us'}
				</h3>
				<div class="mx-auto h-px w-16 bg-gradient-to-r from-transparent via-zinc-300 to-transparent dark:via-zinc-600"></div>
			</div>
			<div class="flex flex-wrap items-center justify-center gap-3 sm:gap-4 md:gap-6">
				<a
					class="group relative flex items-center gap-2 rounded-xl border border-zinc-200/50 bg-white/50 px-4 py-3 text-zinc-600 shadow-sm backdrop-blur-sm transition-all duration-300 hover:border-sky-400/30 hover:bg-sky-50/50 hover:text-sky-600 hover:shadow-lg hover:shadow-sky-400/10 dark:border-zinc-800/50 dark:bg-zinc-900/50 dark:text-zinc-300 dark:hover:border-sky-400/30 dark:hover:bg-sky-900/20 dark:hover:text-sky-400"
					href="https://github.com/gerardbourguett"
					target="_blank"
					rel="noopener noreferrer"
				>
					<Github
						size={20}
						class="transition-all duration-300 group-hover:scale-110 group-hover:rotate-12"
					/>
					<span class="hidden text-sm font-medium sm:inline">{$_('footer.repository') || 'Repository'}</span>
					<Star size={12} class="absolute -top-1 -right-1 text-yellow-400 opacity-0 transition-all duration-300 group-hover:opacity-100 group-hover:scale-110" />
				</a>
				<a
					class="group relative flex items-center gap-2 rounded-xl border border-zinc-200/50 bg-white/50 px-4 py-3 text-zinc-600 shadow-sm backdrop-blur-sm transition-all duration-300 hover:border-amber-400/30 hover:bg-amber-50/50 hover:text-amber-600 hover:shadow-lg hover:shadow-amber-400/10 dark:border-zinc-800/50 dark:bg-zinc-900/50 dark:text-zinc-300 dark:hover:border-amber-400/30 dark:hover:bg-amber-900/20 dark:hover:text-amber-400"
					href="https://ko-fi.com/vanderfondi"
					target="_blank"
					rel="noopener noreferrer"
				>
					<Coffee
						size={20}
						class="transition-all duration-300 group-hover:scale-110 group-hover:rotate-12"
					/>
					<span class="hidden text-sm font-medium sm:inline">{$_('footer.give_me_coffee') || 'Give me a coffee'}</span>
					<Heart size={12} class="absolute -top-1 -right-1 text-red-400 opacity-0 transition-all duration-300 group-hover:opacity-100 group-hover:scale-110" />
				</a>
				<a
					class="group relative flex items-center gap-2 rounded-xl border border-zinc-200/50 bg-white/50 px-4 py-3 text-zinc-600 shadow-sm backdrop-blur-sm transition-all duration-300 hover:border-purple-400/30 hover:bg-purple-50/50 hover:text-purple-600 hover:shadow-lg hover:shadow-purple-400/10 dark:border-zinc-800/50 dark:bg-zinc-900/50 dark:text-zinc-300 dark:hover:border-purple-400/30 dark:hover:bg-purple-900/20 dark:hover:text-purple-400"
					href="https://www.twitch.tv/vanderfondi"
					target="_blank"
					rel="noopener noreferrer"
				>
					<Twitch
						size={20}
						class="transition-all duration-300 group-hover:scale-110 group-hover:rotate-12"
					/>
					<span class="hidden text-sm font-medium sm:inline">{$_('footer.twitch') || 'Twitch'}</span>
					<div class="absolute -top-1 -right-1 h-2 w-2 rounded-full bg-red-500 opacity-0 transition-all duration-300 group-hover:opacity-100 group-hover:animate-pulse"></div>
				</a>
				<a
					class="group relative flex items-center gap-2 rounded-xl border border-zinc-200/50 bg-white/50 px-4 py-3 text-zinc-600 shadow-sm backdrop-blur-sm transition-all duration-300 hover:border-sky-400/30 hover:bg-sky-50/50 hover:text-sky-600 hover:shadow-lg hover:shadow-sky-400/10 dark:border-zinc-800/50 dark:bg-zinc-900/50 dark:text-zinc-300 dark:hover:border-sky-400/30 dark:hover:bg-sky-900/20 dark:hover:text-sky-400"
					href="https://www.twitter.com/vanderfondi"
					target="_blank"
					rel="noopener noreferrer"
				>
					<Twitter
						size={20}
						class="transition-all duration-300 group-hover:scale-110 group-hover:rotate-12"
					/>
					<span class="hidden text-sm font-medium sm:inline">{$_('footer.twitter') || 'Twitter'}</span>
					<Globe size={12} class="absolute -top-1 -right-1 text-blue-400 opacity-0 transition-all duration-300 group-hover:opacity-100 group-hover:scale-110" />
				</a>
			</div>
		</div>

		<!-- Divider -->
		<div class="mb-6 flex items-center justify-center">
			<div class="h-px flex-1 bg-gradient-to-r from-transparent via-zinc-200 to-transparent dark:via-zinc-700"></div>
			<div class="mx-4 flex items-center gap-1 text-zinc-400">
				<Heart size={12} class="text-red-400" />
				<span class="text-xs font-medium">NYE.today</span>
				<Heart size={12} class="text-red-400" />
			</div>
			<div class="h-px flex-1 bg-gradient-to-r from-transparent via-zinc-200 to-transparent dark:via-zinc-700"></div>
		</div>

		<!-- Copyright section -->
		<div class="text-center">
			<p class="mb-2 text-sm text-zinc-600 dark:text-zinc-400">
				© {CURRENT_YEAR + 1} VanderFondi. {$_('footer.made_with') || 'Made with'}
				<Heart size={14} class="mx-1 inline text-red-400" />
				{$_('footer.by') || 'by'} a passionate developer
			</p>
			<p class="text-xs text-zinc-500 dark:text-zinc-500">
				{$_('footer.licensed_under') || 'Licensed under'}
				<a
					href="https://creativecommons.org/licenses/by/4.0/"
					target="_blank"
					rel="noopener noreferrer"
					class="mx-1 font-medium text-sky-500 transition-colors duration-200 hover:text-sky-600 hover:underline dark:text-sky-400 dark:hover:text-sky-300"
					>Creative Commons BY 4.0</a
				>
				• {$_('footer.built_with') || 'Built with SvelteKit & TailwindCSS'}
			</p>
		</div>
	</div>

	<!-- Background decoration -->
	<div class="absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-sky-400/20 via-purple-400/20 to-amber-400/20"></div>
</footer>
