// components/road-to-2026/road-to-2026.tsx
'use client';

import React, { useEffect, useState } from 'react';
import { motion } from 'motion/react';
import { Card, CardContent, CardHeader, CardTitle } from '../ui/card';
import { Separator } from '../ui/separator';
import timezones from '@/data/timezones.json';
import Image from 'next/image';
import '@fontsource/share-tech-mono';

export interface Timezone {
  id: number;
  countryCode: string;
  countryName: string;
  zoneName: string;
  gmtOffset: number;
  timestamp: number;
}

interface GroupedTimezones {
  offset: number;
  formattedOffset: string;
  timezones: Timezone[];
}

export default function RoadTo2026() {
  const [groupedData, setGroupedData] = useState<GroupedTimezones[]>([]);
  const [currentTime, setCurrentTime] = useState<Date>(new Date());

  useEffect(() => {
    const grouped: { [key: number]: Timezone[] } = {};

    const sortedTimezones = [...(timezones as Timezone[])].sort(
      (a, b) => b.gmtOffset - a.gmtOffset,
    );

    sortedTimezones.forEach((timezone) => {
      if (!grouped[timezone.gmtOffset]) {
        grouped[timezone.gmtOffset] = [];
      }
      grouped[timezone.gmtOffset].push(timezone);
    });

    const groupedArray: GroupedTimezones[] = Object.entries(grouped).map(
      ([offsetStr, zones]) => {
        const offset = parseInt(offsetStr, 10);
        const totalSeconds = Math.abs(offset);
        const hours = Math.floor(totalSeconds / 3600);
        const minutes = Math.floor((totalSeconds % 3600) / 60);
        const sign = offset < 0 ? '-' : '+';
        const formattedOffset = `GMT ${sign}${String(hours).padStart(2, '0')}:${String(minutes).padStart(2, '0')}`;

        return {
          offset,
          formattedOffset,
          timezones: zones,
        };
      },
    );

    groupedArray.sort((a, b) => b.offset - a.offset);
    setGroupedData(groupedArray);

    const interval = setInterval(() => {
      setCurrentTime(new Date());
    }, 1000);

    return () => clearInterval(interval);
  }, []);

  const calculateLocalTime = (gmtOffsetSeconds: number): Date => {
    const now = currentTime;
    const localOffsetMs = now.getTimezoneOffset() * 60 * 1000;
    const utcMs = now.getTime() + localOffsetMs;
    const targetOffsetMs = gmtOffsetSeconds * 1000;
    const targetTimeMs = utcMs + targetOffsetMs;
    return new Date(targetTimeMs);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
      // --- CAMBIO PRINCIPAL AQUÍ ---
      className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8" // Añadido max-w, mx-auto y padding
    >
      <h2 className="text-3xl md:text-4xl font-bold text-center mb-10 bg-clip-text text-transparent bg-gradient-to-r from-purple-400 via-blue-400 to-cyan-400 font-['Share_Tech_Mono'] tracking-wider">
        Global Countdown Timezones
      </h2>

      <div className="space-y-12">
        {' '}
        {/* Espacio entre grupos */}
        {groupedData.map((group) => {
          const isPositive = group.offset >= 0;
          const colorClass = isPositive ? 'text-emerald-400' : 'text-rose-400';

          return (
            <div key={group.offset} className="space-y-6">
              {' '}
              {/* Espacio dentro de un grupo */}
              {/* Encabezado del grupo (Sticky opcional) */}
              <div className="flex items-center gap-4 sticky top-0 bg-background/95 backdrop-blur-sm py-3 z-10">
                {' '}
                {/* Fondo con blur */}
                <Separator className="flex-grow bg-gray-700/50" />
                <h3
                  className={`font-['Share_Tech_Mono'] font-semibold ${colorClass} text-lg md:text-xl whitespace-nowrap [text-shadow:0_0_8px_rgba(59,130,246,0.2)]`}
                >
                  {group.formattedOffset}
                </h3>
                <Separator className="flex-grow bg-gray-700/50" />
              </div>
              {/* Grid de tarjetas */}
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
                {group.timezones.map((item: Timezone, index) => {
                  const localTime = calculateLocalTime(item.gmtOffset);

                  return (
                    <motion.div
                      // Usar ID si existe, sino una combinación como fallback
                      key={item.id ?? `${item.zoneName}-${item.countryCode}`}
                      initial={{ opacity: 0, scale: 0.95 }}
                      animate={{ opacity: 1, scale: 1 }}
                      transition={{
                        duration: 0.4,
                        delay: index * 0.04, // Delay escalonado más rápido
                        ease: 'easeOut',
                      }}
                      whileHover={{ y: -4, transition: { duration: 0.2 } }}
                      className="h-full flex" // Asegura que flex funcione para altura completa
                    >
                      {/* Card Styling */}
                      <Card className="w-full flex flex-col bg-gradient-to-br from-gray-900/70 to-black/80 backdrop-blur-md border border-white/10 shadow-lg hover:border-blue-400/50 transition-colors duration-300 rounded-lg overflow-hidden">
                        {' '}
                        {/* Añadido rounded y overflow */}
                        <CardHeader className="flex flex-row items-center gap-3 p-4 pb-2">
                          {' '}
                          {/* Ajustado padding */}
                          <div className="relative h-8 w-12 flex-shrink-0 overflow-hidden rounded-sm shadow-md">
                            <Image
                              src={`/flags/4x3/${item.countryCode.toLowerCase()}.svg`}
                              alt={item.countryName}
                              className="object-cover"
                              fill
                              sizes="(max-width: 640px) 15vw, (max-width: 1024px) 10vw, 8vw" // Tamaños optimizados
                              // Quita unoptimized si no tienes problemas con SVGs en producción
                              // unoptimized={process.env.NODE_ENV === 'development'}
                            />
                          </div>
                          <div className="flex-grow min-w-0">
                            {' '}
                            {/* Añadido min-w-0 para que truncate funcione bien en flex */}
                            <CardTitle
                              className="text-base md:text-lg font-semibold text-gray-100 truncate"
                              title={item.countryName} // Tooltip para nombre completo
                            >
                              {item.countryName}
                            </CardTitle>
                          </div>
                        </CardHeader>
                        <CardContent className="flex-grow flex flex-col justify-between p-4 pt-2">
                          {' '}
                          {/* Ajustado padding */}
                          {/* Info Timezone */}
                          <div className="space-y-1 mb-3">
                            <div className="flex justify-between items-center text-xs md:text-sm gap-2">
                              <span className="text-gray-400 flex-shrink-0">
                                Zone:
                              </span>
                              <span
                                className="font-['Share_Tech_Mono'] text-sky-400 text-right truncate"
                                title={item.zoneName} // Tooltip para nombre completo
                              >
                                {item.zoneName.replace(/_/g, ' ')}
                              </span>
                            </div>
                          </div>
                          {/* Hora Actual */}
                          <div className="flex flex-col items-center border-t border-white/15 pt-3 mt-auto">
                            {' '}
                            {/* mt-auto empuja al fondo */}
                            <span className="text-gray-400 text-xs mb-1">
                              Current Time
                            </span>
                            <span className="font-['Share_Tech_Mono'] text-sky-300 text-2xl font-bold tracking-wider [text-shadow:0_0_10px_rgba(59,130,246,0.4)]">
                              {localTime.toLocaleTimeString('en-GB', {
                                // Formato 24h
                                hour: '2-digit',
                                minute: '2-digit',
                                second: '2-digit',
                                hour12: false,
                              })}
                            </span>
                            <span className="font-['Share_Tech_Mono'] text-gray-500 text-xs">
                              {localTime.toLocaleDateString('en-CA', {
                                // Formato YYYY-MM-DD
                                year: 'numeric',
                                month: '2-digit',
                                day: '2-digit',
                              })}
                            </span>
                          </div>
                        </CardContent>
                      </Card>
                    </motion.div>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>
    </motion.div>
  );
}

// src/lib/components/RoadTo2026.svelte
<script lang="ts">
	import timezoneData from '../data/timezone.json';
	import CardContent from './ui/card/card-content.svelte';
	import CardDescription from './ui/card/card-description.svelte';
	import CardHeader from './ui/card/card-header.svelte';
	import CardTitle from './ui/card/card-title.svelte';
	import Card from './ui/card/card.svelte';
	import { onMount, onDestroy } from 'svelte';

	let timestamp: number = Date.now();

	onMount(() => {
		const interval = setInterval(() => {
			timestamp = Date.now();
		}, 1000); // Actualiza cada segundo

		onDestroy(() => {
			clearInterval(interval);
		});
	});

	function getLocalTime(zoneName: string, timestamp: number): string {
		return new Intl.DateTimeFormat('es-ES', {
			timeZone: zoneName,
			dateStyle: 'full',
			timeStyle: 'medium'
		}).format(new Date(timestamp));
	}

	function getTimeOnly(zoneName: string, timestamp: number): string {
		return new Intl.DateTimeFormat('en-US', {
			timeZone: zoneName,
			hour12: false,
			hour: '2-digit',
			minute: '2-digit'
		}).format(new Date(timestamp));
	}

	function getFlagUrl(countryCode: string): string {
		return `https://hatscripts.github.io/circle-flags/flags/${countryCode.toLowerCase()}.svg`;
	}

	type Zone = (typeof timezoneData)[0];

	function groupByGmtOffset(data: Zone[]) {
		const groups: Record<string, Zone[]> = {};
		for (const zone of data) {
			const key = zone.gmtOffset.toString();
			if (!groups[key]) {
				groups[key] = [];
			}
			groups[key].push(zone);
		}
		return groups;
	}

	const groupedZones = groupByGmtOffset(timezoneData);

	function formatOffset(offset: number): string {
		const hours = offset / 3600;
		return `GMT${hours >= 0 ? '+' : ''}${hours}`;
	}

	function minutesToNextMidnight(zoneName: string, now: number): number {
		const parts = new Intl.DateTimeFormat('en-US', {
			timeZone: zoneName,
			year: 'numeric',
			month: '2-digit',
			day: '2-digit',
			hour: '2-digit',
			minute: '2-digit',
			second: '2-digit',
			hour12: false
		}).formatToParts(new Date(now));

		const getPart = (type: string) => parts.find((p) => p.type === type)?.value || '00';

		const year = Number(getPart('year'));
		const month = Number(getPart('month'));
		const day = Number(getPart('day'));
		const hour = Number(getPart('hour'));
		const minute = Number(getPart('minute'));
		const second = Number(getPart('second'));

		const localNow = new Date(year, month - 1, day, hour, minute, second);
		const nextMidnight = new Date(year, month - 1, day + 1, 0, 0, 0);

		const diffMs = nextMidnight.getTime() - localNow.getTime();
		return Math.floor(diffMs / 60000);
	}

	// Calcula y reordena cada vez que cambia timestamp
	$: groupedEntries = Object.entries(groupedZones).sort(([_, zonesA], [__, zonesB]) => {
		const minutesA = minutesToNextMidnight(zonesA[0].zoneName, timestamp);
		const minutesB = minutesToNextMidnight(zonesB[0].zoneName, timestamp);
		return minutesA - minutesB;
	});

	function getGroupTime(zoneName: string, timestamp: number): string {
		return new Intl.DateTimeFormat('en-US', {
			timeZone: zoneName,
			hour12: false,
			hour: '2-digit',
			minute: '2-digit',
			second: '2-digit'
		}).format(new Date(timestamp));
	}
</script>

<div class="space-y-6 sm:space-y-8">
	<!-- Header -->
	<div class="space-y-3 px-4 text-center sm:space-y-4">
		<h1
			class="bg-gradient-to-r from-sky-400 to-cyan-400 bg-clip-text text-2xl font-bold text-transparent sm:text-3xl lg:text-4xl"
		>
			Road to 2026
		</h1>
		<p class="mx-auto max-w-2xl px-4 text-sm text-zinc-600 sm:text-base dark:text-zinc-400">
			Track the New Year celebrations as they happen around the world. Each timezone celebrates at
			their local midnight.
		</p>
	</div>

	<!-- Timezone Groups -->
	<div class="space-y-6 sm:space-y-8">
		{#each groupedEntries as [offset, zones]}
			<div class="space-y-3 sm:space-y-4">
				<!-- Timezone Header -->
				<div class="flex items-center space-x-2 px-4 sm:space-x-4">
					<div
						class="h-px flex-1 bg-gradient-to-r from-transparent via-sky-400/30 to-transparent"
					></div>
					<div class="flex items-center space-x-2 sm:space-x-3">
						<div class="h-2 w-2 rounded-full bg-sky-400"></div>
						<h2 class="text-lg font-semibold text-sky-400 sm:text-xl">
							{formatOffset(Number(offset))}
						</h2>
						<span class="ml-1 text-xl font-bold text-sky-400 sm:ml-2 sm:text-2xl">
							{getGroupTime(zones[0].zoneName, timestamp)}
						</span>
						<div class="h-2 w-2 rounded-full bg-sky-400"></div>
					</div>
					<div
						class="h-px flex-1 bg-gradient-to-r from-transparent via-sky-400/30 to-transparent"
					></div>
				</div>

				<!-- Cards Grid -->
				<div
					class="grid grid-cols-1 gap-3 px-4 sm:gap-4 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4"
				>
					{#each zones as zone}
						<Card
							class="w-full border-zinc-200/50 bg-white/50 backdrop-blur-sm transition-all duration-300 hover:border-sky-400/30 hover:shadow-lg hover:shadow-sky-400/10 dark:border-zinc-800/50 dark:bg-zinc-900/50 dark:hover:border-sky-400/30"
						>
							<CardHeader class="pb-2 sm:pb-3">
								<div class="flex items-start justify-between gap-2">
									<div class="flex min-w-0 flex-1 items-start space-x-2">
										<!-- Flag -->
										<div class="flex-shrink-0">
											<img
												src={getFlagUrl(zone.countryCode)}
												alt="Flag of {zone.countryName}"
												width="24"
												height="24"
												class="rounded-full shadow-sm sm:h-7 sm:w-7"
												loading="lazy"
											/>
										</div>
										<!-- Country Info -->
										<div class="min-w-0 flex-1 overflow-hidden">
											<CardTitle
												class="block truncate text-xs leading-tight font-semibold text-zinc-900 sm:text-sm dark:text-white"
												title={zone.countryName}
											>
												{zone.countryName}
											</CardTitle>
											<CardDescription
												class="mt-1 block truncate text-xs leading-tight text-zinc-600 dark:text-zinc-400"
												title={zone.zoneName}
											>
												{zone.zoneName}
											</CardDescription>
										</div>
									</div>
									<!-- Time -->
									<div class="flex-shrink-0 text-right">
										<div class="text-base font-bold text-sky-400 sm:text-lg">
											{minutesToNextMidnight(zone.zoneName, timestamp) === 0
												? '<1'
												: minutesToNextMidnight(zone.zoneName, timestamp)}'
										</div>
									</div>
								</div>
							</CardHeader>
							<CardContent class="pt-0">
								<div
									class="flex items-center justify-between gap-2 text-xs text-zinc-500 dark:text-zinc-500"
								>
									<span class="flex-1 truncate" title={`Stream Live in ${zone.countryName}`}>
										Stream Live in {zone.countryName}
									</span>
									<a
										href="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
										target="_blank"
										rel="noopener noreferrer"
										class="flex-shrink-0 text-xs font-medium text-sky-400 transition-colors hover:text-sky-300"
									>
										HERE
									</a>
								</div>
							</CardContent>
						</Card>
					{/each}
				</div>
			</div>
		{/each}
	</div>

	<!-- Footer Info -->
	<div class="border-t border-zinc-200/50 px-4 pt-6 text-center sm:pt-8">
		<p class="text-xs text-zinc-600 sm:text-sm dark:text-zinc-400">
			Times are updated in real-time. Refresh to see current local times.
		</p>
	</div>
</div>
